#include "menus/menu_hundo_saves/include/hundo_saves_menu.h"
#include "gz_flags.h"
#include "save_specials.h"
#include "rels/include/defines.h"
#include "menus/utils/menu_mgr.h"

#ifdef GCN_PLATFORM
static Line lines[HND_SAVES_MAX] = {
    {"goats 1", HND_GOATS_1_INDEX, "Goat herding 1"},
    {"ordon gate clip", HND_ORDON_GATE_CLIP_INDEX, "Gate clip outside Ordon Spring"},
    {"goats 2", HND_GOATS_2_INDEX, "Goat herding 2"},
    {"faron twilight", HND_FARON_TWILIGHT_INDEX, "Faron Twilight tears"},
    {"early master sword", HND_EMS_INDEX, "Super Jump to Sacred Grove"},
    {"purple mist", HND_MIST_INDEX, "Purple mist in Faron Woods (post-EMS)"},
    {"forest bit", HND_FRST_BIT_INDEX, "Back in Time in Forest Temple"},
    {"forest temple 2", HND_FRST_2_INDEX, "The Forest Temple segment after boomerang"},
    {"deku like hp", HND_DEKU_LIKE_INDEX, "Heart piece behind the deku like in west wing"},
    {"diababa", HND_OOKLESS_INDEX, "Forest Temple boss"},
    {"eldin twilight", HND_ELDIN_TWILIGHT_INDEX, "Eldin Twilight tears"},
    {"bomb house skip", HND_BOMB_HOUSE_SKIP_INDEX, "Kakariko Bomb House Skip"},
    {"lanayru gate clip", HND_LANAYRU_GATE_CLIP_INDEX, "Gate Clip to Lanayru"},
    {"pillar clip", HND_PILLAR_CLIP_INDEX, "Pillar Clip in Lake Hylia (low water)"},
    {"lakebed 1", HND_LAKEBED_1_INDEX, "The 1st Lakebed Temple segment"},
    {"deku toad", HND_TOAD_INDEX, "Lakebed Temple miniboss"},
    {"kargorok flight", HND_KARG_INDEX, "Clip OoB with trumpet bird"},
    {"lanayru twilight", HND_LANAYRU_TWILIGHT_INDEX, "Lanayru Twilight tears"},
    {"coro td", HND_COROTD_INDEX, "Text Displacement with Coro"},
    {"early ele", HND_EARLY_ELE_INDEX, "OoB LJA to Death Mountain Elevator"},
    {"goron mines", HND_GM_INDEX, "The Goron Mines segment"},
    {"kitty climb", HND_KITTY_CLIMB_INDEX, "OoB to upper floor of main magnet room"},
    {"dangoro", HND_DANGORO_INDEX, "Goron Mines miniboss"},
    {"fyrus", HND_FYRUS_INDEX, "Goron Mines boss"},
    {"waterfall sidehop", HND_WATERFALL_SIDEHOP_INDEX, "Waterfall sidehop after Rutela skip"},
    {"boss bug", HND_BOSS_BUG_INDEX, "Lanayru Twilight boss bug"},
    {"kb2 skip", HND_KB_2_INDEX, "Clip to skip King Bulblin 2"},
    {"wagon escort", HND_ESCORT_INDEX, "Telma wagon escort"},
    {"escort lja", HND_ESCORT_LJA_INDEX, "LJA over Midna text trigger at the end of escort"},
    {"eldin collection", HND_ELDIN_COLLECT_INDEX, "Eldin Field collection segment"},
    {"lakebed bk skip", HND_LAKEBED_BK_SKIP_INDEX, "Boss Key skip in Lakebed Temple"},
    {"morpheel", HND_MORPHEEL_INDEX, "Lakebed Temple boss"},
    {"mdh tower", HND_MDH_TOWER_INDEX, "MDH tower climb"},
    {"mdh bridge", HND_MDH_BRIDGE_INDEX, "MDH castle rooftops"},
    {"post mdh", HND_POST_MDH_INDEX, "Collection cycle after MDH"},
    {"star 1", HND_STAR_1_INDEX, "The 1st STAR minigame"},
    {"kb1", HND_KB1_INDEX, "King Bulblin 1 fight"},
    {"iza 1 skip", HND_IZA_1_SKIP_INDEX, "Plumm OoB to skip iza 1"},
    {"lake hylia cave", HND_LH_CAVE_INDEX, "Lake Hylia dark cave"},
    {"desert collection", HND_DESERT_COLLECTION_INDEX, "Gerudo Desert collection segment"},
    {"bulblin camp", HND_BULBLIN_CAMP_INDEX, "The camp before Arbiter's Grounds"},
    {"arbiter's grounds", HND_AG_INDEX, "The Arbiter's Grounds segment"},
    {"speed rat", HND_SPEEDRAT_INDEX, "Push the rotary switch and cancel animation using rat"},
    {"poe 1 skip", HND_POE_1_SKIP_INDEX, "The pillar jump in Arbiter's Grounds"},
    {"death sword", HND_DSS_INDEX, "Arbiter's Grounds miniboss"},
    {"stallord", HND_STALLORD_INDEX, "Arbiter's Grounds boss"},
    {"post ag", HND_POST_AG_INDEX, "Collection cycle after Arbiter's"},
    {"snowpeak", HND_SPR_INDEX, "The Snowpeak Ruins segment"},
    {"darkhammer", HND_DARK_HAMMER_INDEX, "Snowpeak Ruins miniboss"},
    {"spr 2", HND_SPR_2_INDEX, "The 2nd half of Snowpeak Ruins"},
    {"freezard 2 skip", HND_FREEZARD_2_INDEX, "Roll past freezard before courtyard 2F"},
    {"spr bk room", HND_SPR_BK_ROOM_INDEX, "Snowpeak Boss Key room"},
    {"blizzeta", HND_BLIZZETA_INDEX, "Snowpeak Ruins boss"},
    {"faron boost", HND_FARON_BOOST_INDEX, "Bomb boost to Sacred Grove"},
    {"grove skip", HND_GROVE_SKIP_INDEX, "Grove 2 skip w/ Moon Boots"},
    {"grove boost", HND_GROVE_BOOST_INDEX, "Boost to upper floor of Grove"},
    {"temple of time", HND_TOT_INDEX, "The Temple of Time segment"},
    {"tot early poe", HND_EARLY_POE_INDEX, "Early poe 1 in Temple of Time"},
    {"tot statue throws", HND_STATUE_THROWS_INDEX, "Temple of Time statue throws"},
    {"tot early hp", HND_EARLY_HP_INDEX, "Boost to heart piece in Temple of Time"},
    {"tot darknut", HND_DARKNUT_INDEX, "Temple of Time miniboss"},
    {"dot skip", HND_DOT_SKIP_INDEX, "Door of Time skip"},
    {"post tot", HND_POST_TOT_INDEX, "Collection cycle after Temple of Time"},
    {"snowboarding", HND_SNOWBOARDING_INDEX, "Yeto and Yeta snowboarding races"},
    {"hotspring minigame", HND_HOTSPRING_INDEX, "Goron hotspring water minigame"},
    {"backslice 100R", HND_ORANGE_RUPEE_BACKSLICE_INDEX, "Backslice to 100R chest in outside SCT"},
    {"gorge arc", HND_GORGE_ARC_INDEX, "Gorge / South Faron collection"},
    {"flight by fowl", HND_FBF_INDEX, "Flight by Fowl minigame heart piece"},
    {"silver rupee", HND_SILVER_RUPEE_INDEX, "Getting the Kakariko Silver Rupee"},
    {"dmt poe", HND_DMT_POE_INDEX, "Poe on the upper ledge of Death Mountain Trail"},
    {"ice puzzle", HND_PUZZLE_INDEX, "The Ice Puzzle segment"},
    {"iza 2", HND_IZA2_INDEX, "Iza River Ride minigame"},
    {"hugo archery", HND_ARCHERY_INDEX, "Archery in Hidden Village"},
    {"city 1", HND_CITY_1_INDEX, "The 1st City in the Sky segment"},
    {"city gate clip", HND_CGC_INDEX, "Clipping through the city gate before Aeralfos"},
    {"aeralfos skip", HND_AERALFOS_INDEX, "the city in the sky miniboss"},
    {"city 2", HND_CITY_2_INDEX, "The 2nd City in the Sky segment"},
    {"early poe cycle", HND_POE_CYCLE_INDEX, "City early poe cycle segment"},
    {"fan tower", HND_FAN_TOWER_INDEX, "Final fan room in City"},
    {"argorok", HND_ARGOROK_INDEX, "City in the Sky boss"},
    {"argorok 2", HND_ARGOROK_2_INDEX, "Argorok's 2nd phase"},
    {"star 2", HND_STAR_2_INDEX, "The 2nd STAR minigame"},
    {"palace 1", HND_PALACE_1_INDEX, "The 1st Palace of Twilight segment"},
    {"palace 2", HND_PALACE_2_INDEX, "The 2nd Palace of Twilight segment"},
    {"early platform cycle", HND_EARLY_PLATFORM_INDEX, "Early platform in Palace of Twilight"},
    {"zant", HND_ZANT_INDEX, "Palace of Twilight boss"},
    {"cave of ordeals", HND_COO_INDEX, "The Cave of Ordeals segment"},
    {"coo floor 10", HND_COO_10_INDEX, "Cave of Ordeals floor 10"},
    {"coo floor 17 poe", HND_COO_17_INDEX, "Cave of Ordeals floor 17 with poe"},
    {"coo floor 20", HND_COO_20_INDEX, "Cave of Ordeals floor 20"},
    {"coo floor 30", HND_COO_30_INDEX, "Cave of Ordeals floor 30"},
    {"coo floor 33 poe", HND_COO_33_INDEX, "Cave of Ordeals floor 33 with poe"},
    {"coo floor 40", HND_COO_40_INDEX, "Cave of Ordeals floor 40"},
    {"cats minigame", HND_CATS_INDEX, "Hidden Village cats minigame"},
    {"hyrule castle", HND_HYRULE_INDEX, "The Hyrule Castle segment"},
    {"darknut skip", HND_DARKNUT_SKIP_INDEX, "Hyrule Castle 1st Darknut skip"},
    {"friendless", HND_FRIENDLESS_INDEX, "Skip pre-BK cutscene with JSLJA"},
    {"final tower", HND_FINAL_TOWER_INDEX, "The tower climb before Ganondorf"},
    {"beast ganon", HND_BEAST_GANON_INDEX, "The Beast Ganon fight"},
    {"horseback ganon", HND_HORSEBACK_GANON_INDEX, "The Horseback Ganondorf fight"},
};

KEEP_FUNC HundoSavesMenu::HundoSavesMenu(Cursor& cursor)
    : Menu(cursor) {}

#elif defined(WII_PLATFORM)
static Line lines[WND_SAVES_MAX] = {
    {"goats 1", WND_GOATS_1_INDEX, "Goat herding 1"},
    {"ordon gate clip", WND_ORDON_GATE_CLIP_INDEX, "Ordon gate clip"},
    {"goats 2", WND_GOATS_2_INDEX, "Goat herding 2"},
    {"sword and shield", WND_SWORD_AND_SHIELD_INDEX, "Ordon nighttime segment"},
    {"faron twilight", WND_FARON_TWILIGHT_INDEX, "Faron Twilight tears"},
    {"early master sword", WND_EMS_INDEX, "Superjump to Sacred Grove"},
    {"purple mist", WND_MIST_INDEX, "Purple mist in Faron Woods (post-EMS)"},
    {"forest bit", WND_FOREST_BIT_INDEX, "BiTE to set EBF in Forest Temple"},
    {"faron escape", WND_FARON_ESCAPE_INDEX, "Escape Faron with a displacement clip and no boots"},
    {"lanayru gate clip", WND_LANAYRU_GATE_CLIP_INDEX, "Clip through the gate to reach Lanayru early"},
    {"midna dive", WND_MIDNA_DIVE_INDEX, "High water midna dive with no boots and a pot"},
    {"jake skip", WND_JAKE_SKIP_INDEX, "2nd room of Lakebed with step clip and no boots or ZA"},
    {"lakebed dcs", WND_LAKEBED_DCS_INDEX, "Lakebed displacement clips"},
    {"deku toad", WND_TOAD_INDEX, "Deku Toad"},
    {"kargorok fight", WND_KARG_FIGHT_INDEX, "Kill the kargorok rider without boots"},
    {"kargorok flight", WND_KARG_FLIGHT_INDEX, "Clip OoB with trumpet bird"},
    {"forest temple 2", WND_FOREST_TEMPLE_INDEX, "Forest Temple 2nd segment with clawshot"},
    {"diababa", WND_DIABABA_INDEX, "Forest Temple boss"},
    {"hfs postman skip", WND_HFS_POSTMAN_SKIP_INDEX, "Golden bug and postman skip in Hyrule Field South"},
    {"eldin twilight", WND_ELDIN_TWILIGHT_INDEX, "Eldin Twilight tears"},
    {"basement bugs", WND_BASEMENT_BUGS_INDEX, "Kakariko Sanctuary basement bugs"},
    {"elde inn", WND_ELDE_INN_INDEX, "Kakariko Elde Inn bugs"},
    {"bomb house skip", WND_BOMBHOUSE_SKIP_INDEX, "Wolf Bomb House Skip"},
    {"eldin steam cycle", WND_ELDIN_STEAM_CYCLE_INDEX, "DMT messenger fight and steam cycle"},
    {"post eldin twilight", WND_POST_ELDIN_TWILIGHT_INDEX, "Collection segment after Eldin Twilight"},
    {"coro td", WND_COROTD_INDEX, "Text Displacement with Coro"},
    {"early elevator", WND_EARLY_ELE_INDEX, "Clip OoB and wolf jump to DMT elevator"},
    {"goron mines", WND_GM_INDEX, "Goron Mines segment"},
    {"key shard skip", WND_KSS_INDEX, "Precise jump to skip 2nd key shard in GM"},
    {"dangoro", WND_DANGORO_INDEX, "Goron Mines miniboss"},
    {"fyrus", WND_FYRUS_INDEX, "Goron Mines boss"},
    {"zd bug", WND_ZD_BUG_INDEX, "Lanayru Twilight bug in upper Zora's Domain"},
    {"waterfall sidehop", WND_WATERFALL_SIDEHOP_INDEX, "Sidehop out of waterfall after Rutela skip"},
    {"ct bug", WND_CT_BUG_INDEX, "Lanayru Twilight bug in Castle Town"},
    {"dock bug", WND_DOCK_BUG_INDEX, "Lanayru Twilight penultimate bug on the dock"},
    {"plumm minigame", WND_PLUMM_INDEX, "Plumm minigame for heart piece"},
    {"iza 1 skip setup", WND_IZA1_SKIP_SETUP_INDEX, "Interrupt rocks blowing up by talking to Iza"},
    {"kb2 skip", WND_KB2_SKIP_INDEX, "Step clip with Epona to skip King Bulblin 2"},
    {"wagon escort", WND_ESCORT_INDEX, "Telma wagon escort"},
    {"kb1 trigger skip", WND_KB1_TRIGGER_SKIP_INDEX, "Skip KB1 trigger at the end of escort"},
    {"pre mdh cleanup", WND_PRE_MDH_CLEANUP_INDEX, "Cleanup before Midna's Desperate Hour"},
    {"lakebed 2", WND_LAKEBED_BK_SKIP_INDEX, "Return trip to Lakebed"},
    {"morpheel", WND_MORPHEEL_INDEX, "Lakebed Temple boss with ZA"},
    {"star 1", WND_STAR1_INDEX, "The 1st STAR minigame"},
    {"louise glitch", WND_LOUISE_GLITCH_INDEX, "B attack to skip camera pan in Louise CS"},
    {"rope skip", WND_ROPE_SKIP_INDEX, "Skip first rope in Telma's bar"},
    {"mdh tower", WND_MDH_TOWER_INDEX, "MDH tower climb"},
    {"mdh bridge", WND_MDH_BRIDGE_INDEX, "MDH castle rooftops"},
    {"post mdh", WND_POST_MDH_INDEX, "Post MDH day/night cycle"},
    {"kb1", WND_KB1_INDEX, "King Bulblin 1 fight with Bow"},
    {"gorge cleanup", WND_GORGE_CLEANUP_INDEX, "Kakariko gorge collection cycle"},
    {"iza 1 skip", WND_IZA1_SKIP_INDEX, "Plumm OoB to finish skipping Iza 1"},
    {"lake hylia cave", WND_LAKE_HYLIA_CAVE_INDEX, "Lake Hylia cave"},
    {"gerudo desert", WND_DESERT_INDEX, "Gerudo Desert collection"},
    {"bulblin camp", WND_BULBLIN_CAMP_INDEX, "Bulblin camp before Arbiter's Grounds"},
    {"arbiter's grounds", WND_AG_INDEX, "Arbiter's Grounds segment"},
    {"poe 1 skip", WND_POE1_SKIP_INDEX, "Skip 1st poe with pillar jump"},
    {"poe 4", WND_POE4_INDEX, "The 4th poe in AG"},
    {"poe 3", WND_POE3_INDEX, "The 3rd poe backwards in AG"},
    {"ag early bk", WND_AG_EARLY_BK_INDEX, "Wolf B attack around collision to get AG boss key early"},
    {"stalfos skip", WND_STALFOS_SKIP_INDEX, "Skip the triple stalfos with 3pcc or step clip"},
    {"death sword", WND_DSS_INDEX, "Death sword fight or skip with superjump"},
    {"stallord", WND_STALLORD_INDEX, "Arbiter's Grounds boss"},
    {"stallord 2", WND_STALLORD2_INDEX, "Stallord's 2nd phase"},
    {"post ag", WND_POST_AG_INDEX, "Collection after Arbiter's Grounds"},
    {"lower zd cleanup", WND_OUTSIDE_ZD_CLEANUP_INDEX, "Cleanup in Zora's Domain before SPR"},
    {"snowpeak", WND_SNOWPEAK_INDEX, "Snowpeak mountain ascent and collection"},
    {"graveyard", WND_GRAVEYARD_INDEX, "Kakariko graveyard collection"},
    {"snowpeak ruins", WND_SPR_INDEX, "Snowpeak Ruins segment"},
    {"darkhammer", WND_DARKHAMMER_INDEX, "Snowpeak Ruins miniboss"},
    {"spr superjump", WND_SPR_SUPERJUMP_INDEX, "Keese superjump to SPR HP"},
    {"lfc", WND_LFC_INDEX, "Ladder Freezard Cancel to reach 2F courtyard"},
    {"spr bk room", WND_SPR_BK_ROOM_INDEX, "SPR chapel room with chilfos and boss key"},
    {"blizzeta", WND_BLIZZETA_INDEX, "Snowpeak Ruins boss"},
    {"faron jsmb", WND_FARON_JSMB_INDEX, "Early Sacred Grove with jump strike moon boots"},
    {"grove skip", WND_GROVE_SKIP_INDEX, "Grove 2 skip with JSMB bomb boost"},
    {"wreckage jsmb", WND_WRECKAGE_JSMB_INDEX, "Early ToT with JSMB up the broken stairs"},
    {"temple of time", WND_TOT_INDEX, "Temple of Time segment"},
    {"tot early poe", WND_EARLY_POE_INDEX, "Early poe 1 in Temple of Time"},
    {"tot statue throws", WND_STATUE_THROWS_INDEX, "ToT statue throws for early HP1"},
    {"tot early hp", WND_EARLY_HP_INDEX, "ToT early HP2 with LHS or alternatives"},
    {"tot bk room", WND_TOT_BK_ROOM_INDEX, "ToT boss key room"},
    {"tot 3rd staircase", WND_TOT_THIRD_STAIRCASE_INDEX, "ToT final staircase before Darknut"},
    {"tot darknut", WND_DARKNUT_INDEX, "ToT miniboss"},
    {"dot skip", WND_DOT_SKIP_INDEX, "Door of Time skip with displacement clip"},
    {"armogohma", WND_GOHMA_INDEX, "Armogohma fight"},
    {"post tot", WND_POST_TOT_INDEX, "Post Temple of Time day/night collection cycle"},
    {"yeta race", WND_YETA_RACE_INDEX, "Snowboarding race vs. Yeta"},
    {"renado's letter", WND_RENADO_INDEX, "Post Renado's letter part of Post ToT"},
    {"hotspring minigame", WND_HOTSPRING_INDEX, "Hot Springwater escort to goron"},
    {"south ct", WND_SCT_INDEX, "South castle town part of post ToT"},
    {"hyrule field cleanup", WND_HF_CLEANUP_INDEX, "Collection in hyrule field during post ToT"},
    {"flight by fowl", WND_FBF_INDEX, "Collection in Lake Hylia from FBF"},
    {"hugo archery", WND_HUGO_ARCHERY_INDEX, "Hidden Village 1 minigame"},
    {"kak bell silver", WND_BELL_SILVER_INDEX, "Kakariko bell silver rupee with BA + rang"},
    {"early city", WND_EARLY_CITY_INDEX, "Statue clip for early City in the Sky"},
    {"city 1", WND_CITY1_INDEX, "City in the Sky segment"},
    {"city east wing", WND_EAST_WING_INDEX, "Ledge hang jumpslash into 3pcc for early aeralfos"},
    {"aeralfos", WND_AERALFOS_INDEX, "Skip aeralfos with 3pcc"},
    {"city 2", WND_CITY2_INDEX, "City in the Sky segment after claws savewarp"},
    {"big baba room", WND_ANNOYING_ROOM_INDEX, "Ascent in big baba room"},
    {"peahat cycle", WND_PEATHAT_LJA_INDEX, "CitS poe cycle and peahat LJA for HP2"},
    {"city bk clip", WND_CITY_BK_CLIP_INDEX, "CitS grate clip from below for boss key"},
    {"fan tower", WND_FAN_TOWER_INDEX, "CitS fan tower ascent"},
    {"argorok", WND_ARGOROK_INDEX, "City in the sky boss"},
    {"argorok 2", WND_ARGOROK2_INDEX, "Argorok's 2nd phase"},
    {"cave of ordeals", WND_COO_INDEX, "Cave of Ordeals segment"},
    {"coo 10", WND_COO_10_INDEX, "Cave of Ordeals from room 10"},
    {"coo 20", WND_COO_20_INDEX, "Cave of Ordeals from room 20"},
    {"coo 30", WND_COO_30_INDEX, "Cave of Ordeals from room 30"},
    {"coo 40", WND_COO_40_INDEX, "Cave of Ordeals from room 40"},
    {"post coo", WND_POST_COO_INDEX, "Post Cave of Ordeals collection"},
    {"boe postman skip", WND_BOE_POSTMAN_SKIP_INDEX, "Skip the postman trigger on Bridge of Eldin"},
    {"cats", WND_CATS_INDEX, "Hidden Village 2 minigame"},
    {"hfn cleanup", WND_HFN_CLEANUP_INDEX, "Hyrule Field North final collection"},
    {"ice cave", WND_ICE_CAVE_INDEX, "Ice block puzzle skips with displacement clips"},
    {"hfn grotto", WND_HFN_GROTTO_INDEX, "Double poe grotto in Hyrule Field North"},
    {"iza 2", WND_IZA2_INDEX, "Iza's 2nd minigame"},
    {"pot 1", WND_POT_INDEX, "Palace of Twilight segment"},
    {"phantom zant 1", WND_PZ1_INDEX, "1st Phantom Zant fight in PoT"},
    {"sol 1 backtrack", WND_BACKTRACK_1_INDEX, "PoT 1st sol retrieval"},
    {"stupid room", WND_STUPID_ROOM_INDEX, "PoT west wing inside 1"},
    {"4head room", WND_SMART_ROOM_INDEX, "PoT west wing inside 2"},
    {"phantom zant 2", WND_PZ2_INDEX, "2nd Phantom Zant fight in PoT"},
    {"sol 2 backtrack", WND_BACKTRACK_2_INDEX, "PoT 2nd sol retrieval"},
    {"after light sword", WND_DOUBLE_SOL_ROOM_INDEX, "PoT double sol room"},
    {"pot bk room", WND_PALACE_BK_ROOM_INDEX, "PoT boss key room"},
    {"early platform", WND_EARLY_PLATFORM_INDEX, "PoT early platform cycle with shield bash"},
    {"zant", WND_ZANT_INDEX, "Palace of Twilight boss"},
    {"zant dangoro", WND_ZANT_DANGORO_INDEX, "Zant's Goron Mines phase"},
    {"zant final", WND_ZANT_FINAL_INDEX, "Zant's Hyrule Castle phase"},
    {"star 2", WND_STAR2_INDEX, "The 2nd STAR minigame"},
    {"hyrule castle", WND_HC_INDEX, "Hyrule Castle segment"},
    {"kb4", WND_KB4_INDEX, "King Bulblin 4 fight with greatspin"},
    {"hc darknut", WND_HC_DARKNUT_INDEX, "Hyrule Castle darknut skip"},
    {"hc aeralfos", WND_HC_AERALFOS_INDEX, "Hyrule Castle aeralfos fight"},
    {"tower climb", WND_HC_TOWER_INDEX, "HC final tower ascent"},
    {"beast ganon", WND_BEAST_GANON_INDEX, "Ganondorf's beast phase"},
    {"horseback ganon", WND_HORSEBACK_GANON_INDEX, "Ganondorf's horseback phase"},
    {"ganondorf", WND_GANONDORF_INDEX, "Do you know how to do an autospin"},
};

KEEP_FUNC HundoSavesMenu::HundoSavesMenu(Cursor& cursor)
    : Menu(cursor) {}

#endif
HundoSavesMenu::~HundoSavesMenu() {}

void HundoSavesMenu::draw() {
#ifdef GCN_PLATFORM
    special HundoSpecials[] = {
        special(HND_GOATS_1_INDEX, SaveMngSpecial_Goats1, NULL),
        special(HND_MIST_INDEX, SaveMngSpecial_PurpleMist, NULL),
        special(HND_KARG_INDEX, SaveMngSpecial_KargOoB, NULL),
        special(HND_EARLY_ELE_INDEX, SaveMngSpecial_EarlyEle, NULL),
        special(HND_KB_2_INDEX, SaveMngSpecial_KB2Skip, NULL),
        special(HND_ESCORT_INDEX, SaveMngSpecial_Escort, SaveMngSpecial_EscortKeys),
        special(HND_ESCORT_LJA_INDEX, SaveMngSpecial_EscortLJA, SaveMngSpecial_EscortKeys),
        special(HND_ELDIN_COLLECT_INDEX, SaveMngSpecial_EldinCollection, NULL),
        special(HND_DANGORO_INDEX, NULL, SaveMngSpecial_Dangoro),
        special(HND_WATERFALL_SIDEHOP_INDEX, SaveMngSpecial_WaterfallSidehop, NULL),
        special(HND_LAKEBED_BK_SKIP_INDEX, SaveMngSpecial_LakebedBKSkip, NULL),
        special(HND_MORPHEEL_INDEX, NULL, SaveMngSpecial_Morpheel),
        special(HND_IZA_1_SKIP_INDEX, SaveMngSpecial_Iza1Skip, NULL),
        special(HND_STALLORD_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Stallord),
        special(HND_DARK_HAMMER_INDEX, SaveMngSpecial_BossFlags, NULL),
        special(HND_SPR_BK_ROOM_INDEX, SaveMngSpecial_SPRBossKey, NULL),
        special(HND_EARLY_POE_INDEX, NULL, SaveMngSpecial_ToTEarlyPoe),
        special(HND_EARLY_HP_INDEX, NULL, SaveMngSpecial_ToTEarlyHP),
        special(HND_POE_CYCLE_INDEX, NULL, SaveMngSpecial_CityPoeCycle),
        special(HND_FAN_TOWER_INDEX, SaveMngSpecial_FanTower, NULL),
        special(HND_ARGOROK_INDEX, NULL, SaveMngSpecial_Argorok),
        special(HND_PALACE_1_INDEX, SaveMngSpecial_Palace1, NULL),
        special(HND_PALACE_2_INDEX, NULL, SaveMngSpecial_Palace2),
        special(HND_COO_INDEX, SaveMngSpecial_CaveOfOrdeals, NULL),
        special(HND_COO_10_INDEX, NULL, SaveMngSpecial_CoO10),
        special(HND_COO_20_INDEX, NULL, SaveMngSpecial_CoO20),
        special(HND_COO_30_INDEX, NULL, SaveMngSpecial_CoO30),
        special(HND_COO_40_INDEX, NULL, SaveMngSpecial_CoO40),
        special(HND_DEKU_LIKE_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_CenterCamera),
        special(HND_OOKLESS_INDEX, SaveMngSpecial_BossFlags, NULL),
        special(HND_FRST_BIT_INDEX, NULL, SaveMngSpecial_ForestBit),
        special(HND_FRST_2_INDEX, SaveMngSpecial_BossFlags, NULL),
        special(HND_KITTY_CLIMB_INDEX, NULL, SaveMngSpecial_KittyClimb),
        special(HND_DMT_POE_INDEX, NULL, NULL, 30 * 1), // delay teleport by 1s
        special(HND_ARGOROK_2_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Argorok2_after),
        special(HND_SNOWBOARDING_INDEX, SaveMngSpecial_RemoveAreaBannerBefore_Snowpeak, NULL),
    };
#endif
#ifdef WII_PLATFORM
    special HundoSpecials[] = {
        special(WND_GOATS_1_INDEX, SaveMngSpecial_Goats1, NULL),
        special(WND_ORDON_GATE_CLIP_INDEX, NULL, SaveMngSpecial_OrdonRock),
        special(WND_KB4_INDEX, NULL, SaveMngSpecial_KB4),
        special(WND_TOAD_INDEX, SaveMngSpecial_BossFlags, NULL),
        special(WND_KARG_FLIGHT_INDEX, SaveMngSpecial_KargOoBWolf, NULL),
        special(WND_MIDNA_DIVE_INDEX, NULL, SaveMngSpecial_MidnaDivePot),
        special(WND_WATERFALL_SIDEHOP_INDEX, SaveMngSpecial_WaterfallSidehop, NULL),
        special(WND_IZA1_SKIP_INDEX, SaveMngSpecial_Iza1Skip, NULL),
        special(WND_PLUMM_INDEX, SaveMngSpecial_Iza1Skip, NULL),
        special(WND_KB2_SKIP_INDEX, SaveMngSpecial_KB2Skip, NULL),
        special(WND_ESCORT_INDEX, SaveMngSpecial_Escort, SaveMngSpecial_EscortKeys),
        special(WND_KB1_TRIGGER_SKIP_INDEX, SaveMngSpecial_KB1TriggerSkip, NULL),
        special(WND_MORPHEEL_INDEX, NULL, SaveMngSpecial_Morpheel),
        special(WND_MDH_BRIDGE_INDEX, SaveMngSpecial_MDHBridge, NULL),
        special(WND_PRE_MDH_CLEANUP_INDEX, SaveMngSpecial_EldinCollection, NULL),
        special(WND_GORGE_CLEANUP_INDEX, SaveMngSpecial_EldinCollection, NULL),
        special(WND_AG_EARLY_BK_INDEX, SaveMngSpecial_AGEarlyBk, NULL),
        special(WND_STALLORD_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Stallord),
        special(WND_STALLORD2_INDEX, SaveMngSpecial_Stallord2_init, SaveMngSpecial_Stallord2),
        special(WND_DARKHAMMER_INDEX, SaveMngSpecial_BossFlags, NULL),
        special(WND_COO_INDEX, SaveMngSpecial_CaveOfOrdeals, NULL),
        special(WND_COO_10_INDEX, NULL, SaveMngSpecial_CoO10),
        special(WND_COO_20_INDEX, NULL, SaveMngSpecial_CoO20),
        special(WND_COO_30_INDEX, NULL, SaveMngSpecial_CoO30),
        special(WND_COO_40_INDEX, NULL, SaveMngSpecial_CoO40),
        special(WND_BEAST_GANON_INDEX, BeastGanonSpecial_setLayer, NULL),
        special(WND_ZANT_DANGORO_INDEX, NULL, SaveMngSpecial_ZantDangoro),
        special(WND_ZANT_FINAL_INDEX, NULL, SaveMngSpecial_ZantFinal),
        special(WND_HFN_GROTTO_INDEX, SaveMngSpecial_HFNGrotto, NULL),
        special(WND_ARGOROK2_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Argorok2_after),
        special(WND_GANONDORF_INDEX, NULL, SaveMngSpecial_Ganondorf)
    };
#endif

    if (GZ_getButtonTrig(BACK_BUTTON)) {
        g_menuMgr->pop();
        return;
    }

    if (GZ_getButtonTrig(SELECTION_BUTTON)) {
        SaveManager::triggerLoad(cursor.y, "hundo", HundoSpecials, ARRAY_COUNT(HundoSpecials));
        g_menuMgr->hide();
    }

    cursor.move(0, MENU_LINE_NUM);
    GZ_drawMenuLines(lines, cursor.y, MENU_LINE_NUM);
}