#ifndef TPGZ_MODULES_FEATURES_EBMB_CHECKER_INCLUDE_EBMB_CHECKER_H
#define TPGZ_MODULES_FEATURES_EBMB_CHECKER_INCLUDE_EBMB_CHECKER_H
namespace EBMBChecker {
void execute();
}  // namespace EBMBChecker

#endif
