#include "menus/menu_any_saves/include/any_saves_menu.h"
#include "gz_flags.h"
#include "save_specials.h"
#include "rels/include/defines.h"
#include "menus/utils/menu_mgr.h"

static Line lines[ANY_SAVES_COUNT] = {
    {"ordon gate clip", ORDON_GATE_CLIP_INDEX, "Gate Clip outside Ordon Spring"},
    {"back in time", BACK_IN_TIME_INDEX, "Back in Time off the Ordon Spring bridge"},
    {"goats", GOATS_INDEX, "Goat herding 2"},
    {"sewers", SEWERS_INDEX, "Hyrule Castle Sewers"},
    {"sewers tower", SEWERS_TOWER_INDEX, "Tower section in Hyrule Castle Sewers"},
    {"rooftops", SEWERS_ROOFTOPS_INDEX, "Hyrule Castle Rooftops"},
    {"sword and shield skip", HUGO_INDEX, "Hangin' with Hugo"},
    {"early master sword", EMS_INDEX, "Super Jump to Sacred Grove"},
    {"purple mist", MIST_INDEX, "Purple mist in Faron Woods (post-EMS)"},
    {"forest bit", FRST_BIT_INDEX, "Back in Time in Forest Temple"},
    {"forest escape", FRST_ESCAPE_INDEX, "LJA over S.Faron exit trigger"},
    {"hfs mailman skip", HFS_MAILMAN_INDEX, "LJA over mailman trigger in Hyrule Field South"},
    {"gorge void", GORGE_VOID_INDEX, "1 frame jump attack into Gorge"},
    {"rupee roll", RUPEE_ROLL_INDEX, "Rupee Roll / Gorge Skip"},
    {"lanayru gate clip", LANAYRU_GATE_CLIP_INDEX, "Gate Clip to Lanayru"},
    {"kargarok fight", KARG_FIGHT_INDEX, "Kill the kargarok rider in Lake Hylia"},
    {"kargarok flight", KARG_INDEX, "Clip OoB with trumpet bird"},
    {"eldin twilight", ELDIN_TWILIGHT_INDEX, "Eldin Twilight tears"},
    {"basement bugs", BASEMENT_BUGS_INDEX, "Kakariko Sanctuary basement bugs"},
    {"elde inn", ELD_INN_INDEX, "Kakariko Village inn bugs"},
    {"bomb house skip", BOMB_HOUSE_SKIP_INDEX, "Skip entering the Bomb House"},
    {"watchtower bug", WATCHTOWER_INDEX, "Bug in the Kakariko watchtower"},
    {"dmt messengers", DMT_BUGS_INDEX, "Death Mountain messenger fight + bugs"},
    {"lanayru twilight", LANAYRU_TWILIGHT_INDEX, "Lanayru Twilight tears"},
    {"inner zd bug", INNER_ZD_BUG_INDEX, "Inner Zora's Domain bug before Rutela skip"},
    {"waterfall sidehop", WATERFALL_SIDEHOP_INDEX, "Waterfall sidehop after Rutela skip"},
    {"castle town bug", CT_BUG_INDEX, "Castle Town bug"},
    {"fyer bug", FYER_BUG_INDEX, "Bug behind Fyer's hut after warping to Lake Hylia"},
    {"dock bug", DOCK_BUG_INDEX, "Last bug by the dock before boss bug"},
    {"boss bug", BOSS_BUG_INDEX, "Lanayru Twilight boss bug"},
    {"zd yellows", ZD_YELLOWS_INDEX, "Get outer Zora's Domain yellows while taking fall damage"},
    {"iza", IZA_INDEX, "Steal Iza's bomb bag"},
    {"plumm cs skip", PLUMM_CS_SKIP_INDEX, "Jump around the Plumm cutscene before howling"},
    {"plumm oob", PLUMM_OOB_INDEX, "Clip OoB during the Plumm flight"},
    {"enter lakebed", ELH_INDEX, "Enter Lakebed with Empty Lake Hylia"},
    {"lakebed", LAKEBED_1_INDEX, "The Lakebed Temple segment"},
    {"wormhole", WORMHOLE_INDEX, "Out of bounds swim to lakebed east outer main room"},
    {"deku toad", TOAD_INDEX, "Lakebed Temple miniboss"},
    {"lakebed bk skip", LAKEBED_BK_SKIP_INDEX, "Boss Key skip in Lakebed Temple"},
    {"morpheel", ONEBOMB_INDEX, "Morpheel fight (no Zora Armor)"},
    {"morpheel 2", MORPHEEL_2_INDEX, "Morpheel phase 2"},
    {"louise glitch", LOUISE_GLITCH_INDEX, "Minor timesave involving Telma's cat during MDH"},
    {"rope skip", ROPE_SKIP_INDEX, "Skip the first two ropes in Telma's Bar during MDH"},
    {"mdh tower", MDH_TOWER_INDEX, "MDH tower climb"},
    {"mdh bridge", MDH_BRIDGE_INDEX, "MDH castle rooftops"},
    {"post mdh", POST_MDH_INDEX, "Right after completing MDH"},
    {"snowpeak cave", SNOWPEAK_CAVE_INDEX, "Transition cave in Snowpeak"},
    {"messenger skip", SPR_WARP_SKIP_INDEX, "LJA to skip the Snowpeak messengers"},
    {"blind snowboarding", BLIND_SNOWBOARDING_INDEX, "Snowboard down the mountain with the fog"},
    {"snowpeak ruins", SPR_INDEX, "The Snowpeak Ruins segment"},
    {"spr floor clip", SPR_FLOOR_CLIP_INDEX, "Vertical floor clip in double freezard room"},
    {"spr displacment clip", SPR_DISPLACEMENT_CLIP_INDEX, "Displacement clip into courtyard main area"},
    {"darkhammer", DARK_HAMMER_INDEX, "Snowpeak Ruins miniboss"},
    {"spr orange 1", SPR_ORANGE_1_INDEX, "Orange rupee from the cheese room armor"},
    {"spr orange 2", SPR_ORANGE_2_INDEX, "Orange rupee from the entrance armor"},
    {"gerudo desert", DESERT_INDEX, "Dash through the desert and take damage from (or avoid) moldorms"},
    {"desert fence clip", FENCE_CLIP_INDEX, "Clip through the second fence before Bulblin Camp"},
    {"bulblin camp", BULBLIN_CAMP_INDEX, "The camp before Arbiter's Grounds"},
    {"arbiter's grounds", AG_INDEX, "The Arbiter's Grounds segment"},
    {"poe gate clip", POE_GATE_CLIP_INDEX, "Clipping through the Arbiter's poe gate"},
    {"ag early bk", AG_EARLY_BK_INDEX, "Early Boss Key in Arbiter's Grounds"},
    {"human movement", AG_HUMAN_MVT_INDEX, "Navigate backwards through epic spinner room"},
    {"stalfos skip", AG_TSS_INDEX, "Triple Stalfos Skip before Death Sword"},
    {"death sword", DSS_INDEX, "Arbiter's Grounds miniboss"},
    {"epic spinner room", EPIC_SPINNER_INDEX, "Backtrack to Stallord via epic spinner room"},
    {"stallord", STALLORD_INDEX, "Arbiter's Grounds boss"},
    {"stallord cad", STALLORD_CAD_INDEX, "Clawshot actor displacement using Joseph the staltroop"},
    {"stallord dc", STALLORD_CLIP_INDEX, "Displacement clip into the first wall before clawshotting Joseph"},
    {"stallord 2", STALLORD2_INDEX, "Stallord 2nd phase"},
    {"mirror chamber", MIRROR_CHAMBER_INDEX, "Mirror Chamber portal messenger fight"},
    {"city early", CITS_EARLY_INDEX, "Clip to the cannon early"},
    {"city 1", CITS_1_INDEX, "The 1st City in the Sky segment"},
    {"argorok cs skip", ARG_CS_SKIP_INDEX, "Argorok cutscene skip during City in the Sky"},
    {"city east wing", CITS_EAST_INDEX, "City in the Sky segment starting at east wing inside"},
    {"city gate clip", CITY_GATE_CLIP_INDEX, "Clipping through the city gate before Aeralfos"},
    {"aeralfos skip", AERALFOS_SKIP_INDEX, "City in the Sky miniboss"},
    {"city 2", CITS_2_INDEX, "The 2nd City in the Sky segment"},
    {"city bk clip", CITS_BK_CLIP_INDEX, "Boss Key clip during City in the Sky"},
    {"fan tower", FAN_TOWER_INDEX, "Final fan room in City"},
    {"argorok", ARGOROK_INDEX, "City in the Sky boss"},
    {"argorok 2", ARGOROK_2_INDEX, "City in the Sky boss's 2nd phase"},
    {"palace 1", PALACE_1_INDEX, "The 1st Palace of Twilight segment"},
    {"phantom zant 1", PZ1_INDEX, "West wing Phantom Zant fight"},
    {"sol 1 backtrack", SOL_1_BACKTRACK_INDEX, "Backtrack with sol after first phantom zant"},
    {"sol 1 throw", SOL_1_THROW_INDEX, "Diagonal sol throw in west wing 2 backtrack"},
    {"stupid room", STUPID_ROOM_INDEX, "First east wing room in Palace of Twilight"},
    {"4head room", SMART_ROOM_INDEX, "Second east wing room in Palace of Twilight"},
    {"phantom zant 2", PZ2_INDEX, "East wing Phantom Zant fight"},
    {"sol 2 backtrack", SOL_2_BACKTRACK_INDEX, "Backtrack with sol after second phantom zant"},
    {"after light sword", PALACE_2_INDEX, "The Palace of Twilight segment after getting Light Sword"},
    {"palace bk room", PALACE_BK_INDEX, "Palace of Twilight outdoor boss key room"},
    {"early platform", EARLY_PLATFORM_INDEX, "Early platform in Palace of Twilight"},
    {"zant", ZANT_INDEX, "Palace of Twilight boss"},
    {"zant dangoro", ZANT_DANGORO_INDEX, "Goron Mines phase of the Zant fight"},
    {"zant final", ZANT_FINAL_INDEX, "Hyrule Castle phase of the Zant fight"},
    {"ct mailman skip", HC_MAILMAN_INDEX, "The mailman skip before Hyrule Castle"},
    {"hyrule castle", HC_INDEX, "The Hyrule Castle segment"},
    {"kb4", KB4_INDEX, "The final King Bulblin fight"},
    {"hc chandeliers", HC_INSIDE_INDEX, "After entering Hyrule Castle indoors"},
    {"darknut fight", DARKNUT_INDEX, "The 1st Darknut fight in Hyrule Castle"},
    {"hc lantern puzzle", HC_TORCH_INDEX, "Hyrule Castle lantern puzzle in east wing 1"},
    {"hc dynalfos", HC_DYNALFOS_INDEX, "Hyrule Castle double dynalfos in east wing 2"},
    {"hc aeralfos", HC_AERALFOS_INDEX, "The aeralfos fight before the Hyrule Castle boss key"},
    {"final tower climb", HC_TOWER_INDEX, "The tower climb before Ganondorf"},
    {"beast ganon", BEAST_GANON_INDEX, "The Beast Ganon fight"},
    {"horseback ganon", HORSEBACK_GANON_INDEX, "The Horseback Ganondorf fight"},
    {"ganondorf", GANONDORF_INDEX, "Do you know how to do an autospin"},
};

KEEP_FUNC AnySavesMenu::AnySavesMenu(Cursor& cursor)
    : Menu(cursor) {}

AnySavesMenu::~AnySavesMenu() {}

void AnySavesMenu::draw() {
    if (GZ_getButtonTrig(BACK_BUTTON)) {
        g_menuMgr->pop();
        return;
    }

    if (GZ_getButtonTrig(SELECTION_BUTTON)) {
        special AnySpecials[] = {
            special(ORDON_GATE_CLIP_INDEX, NULL, SaveMngSpecial_OrdonRock),
            special(HUGO_INDEX, SaveMngSpecial_Hugo, SaveMngSpecial_SpawnHugo),
            special(KARG_INDEX, SaveMngSpecial_KargOoB, NULL),
            special(PLUMM_OOB_INDEX, SaveMngSpecial_AnyPlummOoB, NULL),
            special(LAKEBED_BK_SKIP_INDEX, SaveMngSpecial_LakebedBKSkip, NULL),
            special(ONEBOMB_INDEX, NULL, SaveMngSpecial_Morpheel),
            special(STALLORD_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Stallord),
            special(STALLORD_CAD_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_StallordCad),
            special(STALLORD_CLIP_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_StallordDisplacementClip),
            special(STALLORD2_INDEX, SaveMngSpecial_Stallord2_init, SaveMngSpecial_Stallord2),
            special(ZANT_DANGORO_INDEX, NULL, SaveMngSpecial_ZantDangoro),
            special(ZANT_FINAL_INDEX, NULL, SaveMngSpecial_ZantFinal),
            special(FRST_ESCAPE_INDEX, SaveMngSpecial_BossFlags, NULL),
            special(RUPEE_ROLL_INDEX, SaveMngSpecial_BossFlags, NULL),
            special(LANAYRU_GATE_CLIP_INDEX, SaveMngSpecial_BossFlags, NULL),
            special(LAKEBED_1_INDEX, SaveMngSpecial_BossFlags, NULL),
            special(TOAD_INDEX, SaveMngSpecial_BossFlags, NULL),
            special(WATERFALL_SIDEHOP_INDEX, SaveMngSpecial_WaterfallSidehop, NULL),
            special(DARK_HAMMER_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Darkhammer),
            special(FRST_BIT_INDEX, NULL, SaveMngSpecial_ForestBit),
            special(FAN_TOWER_INDEX, SaveMngSpecial_FanTower, NULL),
            special(ARGOROK_INDEX, SaveMngSpecial_Argorok, NULL),
            special(PALACE_1_INDEX, SaveMngSpecial_Palace1, NULL),
            special(PALACE_2_INDEX, NULL, SaveMngSpecial_Palace2),
            special(BEAST_GANON_INDEX, BeastGanonSpecial_setLayer, NULL),
            special(ELH_INDEX, SaveMngSpecial_emptyLake, NULL),
            special(IZA_INDEX, SaveMngSpecial_BossFlags, NULL),
            special(DSS_INDEX, NULL, SaveMngSpecial_DeathSword),
            special(ARG_CS_SKIP_INDEX, NULL, SaveMngSpecial_ArgorokCSSkip),
            special(PALACE_BK_INDEX, NULL, SaveMngSpecial_PalaceBossKey),
            special(EARLY_PLATFORM_INDEX, NULL, SaveMngSpecial_EarlyPlatform),
            special(KB4_INDEX, NULL, SaveMngSpecial_KB4),
            special(AERALFOS_SKIP_INDEX, NULL, SaveMngSpecial_Aeralfos),
            special(WATCHTOWER_INDEX, SaveMngSpecial_SetDigging, NULL),
            special(ZD_YELLOWS_INDEX, SaveMngSpecial_ZD_Yellows, SaveMngSpecial_ZD_Yellows),
            special(ROPE_SKIP_INDEX, SaveMngSpecial_RopeSkip, NULL),
            special(MDH_BRIDGE_INDEX, SaveMngSpecial_MDHBridge, NULL),
            special(SNOWPEAK_CAVE_INDEX, SaveMngSpecial_SetDigging, NULL),
            special(AG_EARLY_BK_INDEX, SaveMngSpecial_AGEarlyBk, NULL),
            special(SOL_1_THROW_INDEX, SaveMngSpecial_HoldSol, NULL),
            special(ARGOROK_2_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Argorok2_after),
            special(GANONDORF_INDEX, NULL, SaveMngSpecial_Ganondorf),
            special(ELDIN_TWILIGHT_INDEX, NULL, SaveMngSpecial_ZD_Yellows),
            special(BASEMENT_BUGS_INDEX, NULL, SaveMngSpecial_ZD_Yellows),
            special(ELD_INN_INDEX, NULL, SaveMngSpecial_ZD_Yellows),
            special(FYER_BUG_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(SMART_ROOM_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(HFS_MAILMAN_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(PLUMM_CS_SKIP_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(SPR_WARP_SKIP_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(SPR_DISPLACEMENT_CLIP_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(AG_HUMAN_MVT_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(AG_TSS_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(MIRROR_CHAMBER_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(CITY_GATE_CLIP_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(CITS_BK_CLIP_INDEX, NULL, SaveMngSpecial_CenterCamera),
            special(SOL_1_BACKTRACK_INDEX, NULL, SaveMngSpecial_SolBacktrackCamera),
            special(SOL_2_BACKTRACK_INDEX, NULL, SaveMngSpecial_SolBacktrackCamera),
            special(GORGE_VOID_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_GorgeVoid),
            special(MORPHEEL_2_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Morpheel2),
        };
        SaveManager::triggerLoad(cursor.y, "any", AnySpecials, ARRAY_COUNT(AnySpecials));
        g_menuMgr->hide();
    }

    cursor.move(0, ARRAY_COUNT(lines));
    GZ_drawMenuLines(lines, cursor.y, ARRAY_COUNT(lines));
}
