#include "menus/menu_any_saves/include/any_saves_menu.h"
#include "gz_flags.h"
#include "save_specials.h"
#include "rels/include/defines.h"
#include "menus/utils/menu_mgr.h"

KEEP_FUNC AnySavesMenu::AnySavesMenu(Cursor& cursor)
    : Menu(cursor),
      lines{
          {"ordon gate clip", ORDON_GATE_CLIP_INDEX, "Gate Clip outside Ordon Spring"},
          {"back in time", BACK_IN_TIME_INDEX, "Back in Time off the Ordon Spring bridge"},
          {"goats", GOATS_INDEX, "Goat herding 2"},
          {"sewers", SEWERS_INDEX, "Hyrule Castle Sewers"},
          {"sewers tower", SEWERS_TOWER_INDEX, "Tower section in Hyrule Castle Sewers"},
          {"rooftops", SEWERS_ROOFTOPS_INDEX, "Hyrule Castle Rooftops"},
          {"sword and shield skip", HUGO_INDEX, "Hangin' with Hugo"},
          {"early master sword", EMS_INDEX, "Super Jump to Sacred Grove"},
          {"purple mist", MIST_INDEX, "Purple mist in Faron Woods (post-EMS)"},
          {"forest bit", FRST_BIT_INDEX, "Back in Time in Forest Temple"},
          {"forest escape", FRST_ESCAPE_INDEX, "LJA over S.Faron exit trigger"},
          {"gorge void", GORGE_VOID_INDEX, "1 frame jump attack into Gorge"},
          {"rupee roll", RUPEE_ROLL_INDEX, "Rupee Roll / Gorge Skip"},
          {"lanayru gate clip", LANAYRU_GATE_CLIP_INDEX, "Gate Clip to Lanayru"},
          {"kargarok fight", KARG_FIGHT_INDEX, "Kill the kargarok rider in Lake Hylia"},
          {"kargarok flight", KARG_INDEX, "Clip OoB with trumpet bird"},
          {"eldin twilight", ELDIN_TWILIGHT_INDEX, "Eldin Twilight tears"},
          {"basement bugs", BASEMENT_BUGS_INDEX, "Kakariko Sanctuary basement bugs"},
          {"eld inn", ELD_INN_INDEX, "Kakariko Village inn bugs"},
          {"bomb house skip", BOMB_HOUSE_SKIP_INDEX, "Skip entering the Bomb House"},
          {"lanayru twilight", LANAYRU_TWILIGHT_INDEX, "Lanayru Twilight tears"},
          {"inner zd bug", INNER_ZD_BUG_INDEX, "Inner Zora's Domain bug before Rutela skip"},
          {"waterfall sidehop", WATERFALL_SIDEHOP_INDEX, "Waterfall sidehop after Rutela skip"},
          {"castle town bug", CT_BUG_INDEX, "Castle Town bug"},
          {"dock bug", DOCK_BUG_INDEX, "Last bug by the dock before boss bug"},
          {"boss bug", BOSS_BUG_INDEX, "Lanayru Twilight boss bug"},
          {"iza", IZA_INDEX, "Steal Iza's bomb bag"},
          {"plumm oob", PLUMM_OOB_INDEX, "Clip OoB during the Plumm flight"},
          {"enter lakebed", ELH_INDEX, "Enter Lakebed with Empty Lake Hylia"},
          {"lakebed", LAKEBED_1_INDEX, "The Lakebed Temple segment"},
          {"wormhole", WORMHOLE_INDEX, "Out of bounds swim to lakebed east outer main room"},
          {"deku toad", TOAD_INDEX, "Lakebed Temple miniboss"},
          {"lakebed bk skip", LAKEBED_BK_SKIP_INDEX, "Boss Key skip in Lakebed Temple"},
          {"morpheel", ONEBOMB_INDEX, "Morpheel fight (no Zora Armor)"},
          {"louise glitch", LOUISE_GLITCH_INDEX, "Minor timesave involving Telma's cat during MDH"},
          {"rope skip", ROPE_SKIP_INDEX, "Skip the first two ropes in Telma's Bar during MDH"},
          {"mdh tower", MDH_TOWER_INDEX, "MDH tower climb"},
          {"mdh bridge", MDH_BRIDGE_INDEX, "MDH castle rooftops"},
          {"post mdh", POST_MDH_INDEX, "Right after completing MDH"},
          {"snowpeak cave", SNOWPEAK_CAVE_INDEX, "Transition cave in Snowpeak"},
          {"messenger skip", SPR_WARP_SKIP_INDEX, "LJA to skip the Snowpeak messengers"},
          {"blind snowboarding", BLIND_SNOWBOARDING_INDEX, "Snowboard down the mountain with the fog"},
          {"snowpeak ruins", SPR_INDEX, "The Snowpeak Ruins segment"},
          {"lfc", LFC_INDEX, "Ladder Freezard Cancel in SPR"},
          {"darkhammer", DARK_HAMMER_INDEX, "Snowpeak Ruins miniboss"},
          {"desert fence clip", FENCE_CLIP_INDEX, "Clip through the second fence before Bulblin Camp"},
          {"bulblin camp", BULBLIN_CAMP_INDEX, "The camp before Arbiter's Grounds"},
          {"arbiter's grounds", AG_INDEX, "The Arbiter's Grounds segment"},
          {"poe gate clip", POE_GATE_CLIP_INDEX, "Clipping through the Arbiter's poe gate"},
          {"ag early bk", AG_EARLY_BK_INDEX, "Early Boss Key in Arbiter's Grounds"},
          {"stalfos skip", AG_TSS_INDEX, "Triple Stalfos Skip before Death Sword"},
          {"death sword", DSS_INDEX, "Arbiter's Grounds miniboss"},
          {"epic spinner room", EPIC_SPINNER_INDEX, "Backtrack to Stallord via epic spinner room"},
          {"stallord", STALLORD_INDEX, "Arbiter's Grounds boss"},
          {"stallord cad", STALLORD_CAD_INDEX, "Clawshot actor displacement using Joseph the staltroop"},
          {"stallord wall clip", STALLORD_CLIP_INDEX, "Clip through the first wall with an L slide"},
          {"stallord bomb boost", STALLORD_BOOST_INDEX, "Clip through the last wall with bomb boost"},
          {"stallord 2", STALLORD2_INDEX, "Stallord 2nd phase"},
          {"mirror chamber", MIRROR_CHAMBER_INDEX, "Mirror Chamber portal messenger fight"},
          {"city early", CITS_EARLY_INDEX, "Clip to the cannon early"},
          {"city 1", CITS_1_INDEX, "The 1st City in the Sky segment"},
          {"argorok cs skip", ARG_CS_SKIP_INDEX, "Argorok cutscene skip during City in the Sky"},
          {"city east wing", CITS_EAST_INDEX, "City in the Sky segment starting at east wing inside"},
          {"city gate clip", CITY_GATE_CLIP_INDEX, "Clipping through the city gate before Aeralfos"},
          {"aeralfos skip", AERALFOS_SKIP_INDEX, "City in the Sky miniboss"},
          {"city 2", CITS_2_INDEX, "The 2nd City in the Sky segment"},
          {"city bk clip", CITS_BK_CLIP_INDEX, "Boss Key clip during City in the Sky"},
          {"fan tower", FAN_TOWER_INDEX, "Final fan room in City"},
          {"argorok", ARGOROK_INDEX, "City in the Sky boss"},
          {"palace 1", PALACE_1_INDEX, "The 1st Palace of Twilight segment"},
          {"phantom zant 1", PZ1_INDEX, "West wing Phantom Zant fight"},
          {"stupid room", STUPID_ROOM_INDEX, "First east wing room in Palace of Twilight"},
          {"smart room", SMART_ROOM_INDEX, "Second east wing room in Palace of Twilight"},
          {"phantom zant 2", PZ2_INDEX, "East wing Phantom Zant fight"},
          {"after light sword", PALACE_2_INDEX, "The Palace of Twilight segment after getting Light Sword"},
          {"palace bk room", PALACE_BK_INDEX, "Palace of Twilight outdoor boss key room"},
          {"early platform", EARLY_PLATFORM_INDEX, "Early platform in Palace of Twilight"},
          {"zant", ZANT_INDEX, "Palace of Twilight boss"},
          {"zant dangoro", ZANT_DANGORO_INDEX, "Goron Mines phase of the Zant fight"},
          {"zant final", ZANT_FINAL_INDEX, "Hyrule Castle phase of the Zant fight"},
          {"ct mailman skip", HC_MAILMAN_INDEX, "The mailman skip before Hyrule Castle"},
          {"hyrule castle", HC_INDEX, "The Hyrule Castle segment"},
          {"kb4", KB4_INDEX, "The final King Bulblin fight"},
          {"darknut fight", DARKNUT_INDEX, "The 1st Darknut fight in Hyrule Castle"},
          {"hc aeralfos", HC_AERALFOS_INDEX, "The aeralfos fight before the Hyrule Castle boss key"},
          {"final tower climb", HC_TOWER_INDEX, "The tower climb before Ganondorf"},
          {"beast ganon", BEAST_GANON_INDEX, "The Beast Ganon fight"},
          {"horseback ganon", HORSEBACK_GANON_INDEX, "The Horseback Ganondorf fight"},
      } {}

AnySavesMenu::~AnySavesMenu() {}

void AnySavesMenu::draw() {
    if (GZ_getButtonTrig(BACK_BUTTON)) {
        g_menuMgr->pop();
        return;
    }

    if (GZ_getButtonTrig(SELECTION_BUTTON)) {
        special AnySpecials[] = {
            special(ORDON_GATE_CLIP_INDEX, nullptr, SaveMngSpecial_OrdonRock),
            special(HUGO_INDEX, SaveMngSpecial_Hugo, SaveMngSpecial_SpawnHugo),
            special(KARG_INDEX, SaveMngSpecial_KargOoB, nullptr),
            special(PLUMM_OOB_INDEX, SaveMngSpecial_AnyPlummOoB, nullptr),
            special(LAKEBED_BK_SKIP_INDEX, SaveMngSpecial_LakebedBKSkip, nullptr),
            special(ONEBOMB_INDEX, nullptr, SaveMngSpecial_Morpheel),
            special(STALLORD_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Stallord),
            special(STALLORD_CAD_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_StallordCad),
            special(STALLORD_CLIP_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_StallordWallClip),
            special(STALLORD_BOOST_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_StallordBombBoost),
            special(STALLORD2_INDEX, SaveMngSpecial_Stallord2_init, SaveMngSpecial_Stallord2),
            special(ZANT_DANGORO_INDEX, nullptr, SaveMngSpecial_ZantDangoro),
            special(ZANT_FINAL_INDEX, nullptr, SaveMngSpecial_ZantFinal),
            special(FRST_ESCAPE_INDEX, SaveMngSpecial_BossFlags, nullptr),
            special(GORGE_VOID_INDEX, SaveMngSpecial_BossFlags, nullptr),
            special(RUPEE_ROLL_INDEX, SaveMngSpecial_BossFlags, nullptr),
            special(LANAYRU_GATE_CLIP_INDEX, SaveMngSpecial_BossFlags, nullptr),
            special(LAKEBED_1_INDEX, SaveMngSpecial_BossFlags, nullptr),
            special(TOAD_INDEX, SaveMngSpecial_BossFlags, nullptr),
            special(WATERFALL_SIDEHOP_INDEX, SaveMngSpecial_WaterfallSidehop, nullptr),
            special(DARK_HAMMER_INDEX, SaveMngSpecial_BossFlags, SaveMngSpecial_Darkhammer),
            special(FRST_BIT_INDEX, nullptr, SaveMngSpecial_ForestBit),
            special(FAN_TOWER_INDEX, SaveMngSpecial_FanTower, nullptr),
            special(ARGOROK_INDEX, SaveMngSpecial_Argorok, nullptr),
            special(PALACE_1_INDEX, SaveMngSpecial_Palace1, nullptr),
            special(PALACE_2_INDEX, nullptr, SaveMngSpecial_Palace2),
            special(BEAST_GANON_INDEX, BeastGanonSpecial_setLayer, nullptr),
            special(ELH_INDEX, SaveMngSpecial_emptyLake, nullptr),
            special(IZA_INDEX, SaveMngSpecial_BossFlags, nullptr),
            special(DSS_INDEX, nullptr, SaveMngSpecial_DeathSword),
            special(ARG_CS_SKIP_INDEX, nullptr, SaveMngSpecial_ArgorokCSSkip),
            special(PALACE_BK_INDEX, nullptr, SaveMngSpecial_PalaceBossKey),
            special(EARLY_PLATFORM_INDEX, nullptr, SaveMngSpecial_EarlyPlatform),
            special(KB4_INDEX, nullptr, SaveMngSpecial_KB4),
            special(AERALFOS_SKIP_INDEX, nullptr, SaveMngSpecial_Aeralfos),
        };
        SaveManager::triggerLoad(cursor.y, "any", AnySpecials, ARRAY_COUNT(AnySpecials));
        g_menuMgr->hide();
    }

    cursor.move(0, ARRAY_COUNT(lines));
    GZ_drawMenuLines(lines, cursor.y, ARRAY_COUNT(lines));
}
