find_package(Python3 REQUIRED COMPONENTS Interpreter)

set(TPGZ_DECOMP_DIR ${CMAKE_SOURCE_DIR}/tp)
set(TPGZ_TOOLS_DIR ${CMAKE_BINARY_DIR}/tools)

file(READ ${TPGZ_DECOMP_DIR}/configure.py TPGZ_DECOMP_CONFIGURE)
string(REGEX MATCH "config\\.compilers_tag = \"([^\"]+)\"" _ ${TPGZ_DECOMP_CONFIGURE})
set(TPGZ_COMPILERS_TAG ${CMAKE_MATCH_1})
string(REGEX MATCH "config\\.wibo_tag = \"([^\"]+)\"" _ ${TPGZ_DECOMP_CONFIGURE})
set(TPGZ_WIBO_TAG ${CMAKE_MATCH_1})

function(tpgz_download_tool tool output tag)
    if(NOT EXISTS ${output})
        file(MAKE_DIRECTORY ${TPGZ_TOOLS_DIR})
        execute_process(
            COMMAND ${Python3_EXECUTABLE} ${TPGZ_DECOMP_DIR}/tools/download_tool.py ${tool} ${output} --tag ${tag}
            RESULT_VARIABLE result)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Failed to download ${tool} ${tag}")
        endif()
    endif()
endfunction()

if(DEFINED TPGZ_COMPILERS_DIR)
    set(TPGZ_MW_COMPILERS ${TPGZ_COMPILERS_DIR})
else()
    set(TPGZ_MW_COMPILERS ${TPGZ_TOOLS_DIR}/compilers_${TPGZ_COMPILERS_TAG})
    tpgz_download_tool(compilers ${TPGZ_MW_COMPILERS} ${TPGZ_COMPILERS_TAG})
endif()

cmake_host_system_information(RESULT TPGZ_HOST_OS QUERY OS_NAME)
cmake_host_system_information(RESULT TPGZ_HOST_ARCH QUERY OS_PLATFORM)
if(NOT DEFINED TPGZ_MW_WRAPPER)
    if(TPGZ_HOST_OS STREQUAL "Windows")
        set(TPGZ_MW_WRAPPER "")
    elseif(TPGZ_HOST_OS STREQUAL "Linux" AND TPGZ_HOST_ARCH MATCHES "x86_64|AMD64|i.86")
        set(TPGZ_MW_WRAPPER ${TPGZ_TOOLS_DIR}/wibo_${TPGZ_WIBO_TAG})
        tpgz_download_tool(wibo ${TPGZ_MW_WRAPPER} ${TPGZ_WIBO_TAG})
        file(CHMOD ${TPGZ_MW_WRAPPER} PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    else()
        find_program(TPGZ_MW_WRAPPER wine REQUIRED)
    endif()
endif()

if(PLATFORM STREQUAL "GCN")
    set(TPGZ_MW_CC_VERSION GC/2.7)
    set(TPGZ_MW_LD_VERSION GC/2.7)
else()
    set(TPGZ_MW_CC_VERSION GC/3.0a3p1)
    set(TPGZ_MW_LD_VERSION GC/3.0a5)
endif()

set(TPGZ_MWCC ${TPGZ_MW_COMPILERS}/${TPGZ_MW_CC_VERSION}/mwcceppc.exe)
set(TPGZ_MWLD ${TPGZ_MW_COMPILERS}/${TPGZ_MW_LD_VERSION}/mwldeppc.exe)

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR powerpc)

foreach(lang C CXX)
    set(CMAKE_${lang}_COMPILER ${TPGZ_MWCC})
    set(CMAKE_${lang}_COMPILER_ID MWCC)
    set(CMAKE_${lang}_COMPILER_ID_RUN TRUE)
    set(CMAKE_${lang}_COMPILER_FORCED TRUE)
    set(CMAKE_${lang}_COMPILER_WORKS TRUE)
    set(CMAKE_${lang}_OUTPUT_EXTENSION .o)
    set(CMAKE_${lang}_COMPILE_OBJECT "${TPGZ_MW_WRAPPER} <CMAKE_${lang}_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -c <SOURCE> -o <OBJECT>")
    set(CMAKE_${lang}_LINK_EXECUTABLE "${TPGZ_MW_WRAPPER} ${TPGZ_MWLD} <LINK_FLAGS> <OBJECTS> -o <TARGET>")
    set(CMAKE_INCLUDE_FLAG_${lang} "-I")
    set(CMAKE_INCLUDE_SYSTEM_FLAG_${lang} "-I")
    set(CMAKE_${lang}_FLAGS_INIT "")
endforeach()
set(CMAKE_EXECUTABLE_SUFFIX .plf)
